export const GET_GUID_BEGIN = 'GET_GUID_BEGIN'

export const MENU_INFO_SET = 'MENU_INFO_SET'

export default {

  MENU_INFO_SET: 'MENU_INFO_SET',
  MENU_INFO_INIT: "MENU_INFO_INIT",
  ALERT_TIP: 'ALERT_TIP',
  CUSTOMALERTTIP:'CUSTOMALERTTIP',
  LOGINWITHCODE:'LOGINWITHCODE',
  // USERINFO:'USERINFO',

}
